# Используем Node.js как базовый образ
FROM node:18-alpine AS builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY . .

# Аргументы сборки для переменных окружения
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SECRET_KEY
ARG SUPABASE_JWT_SECRET
ARG DATABASE_URL
ARG NEXT_PUBLIC_TELEGRAM_BOT_USERNAME
ARG TELEGRAM_BOT_TOKEN
ARG TELEGRAM_WEBHOOK_SECRET
ARG TELEGRAM_USER_SECRET
ARG NEXT_PUBLIC_APP_URL
ARG PORT

# Устанавливаем переменные окружения для сборки
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
ENV SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
ENV DATABASE_URL=${DATABASE_URL}
ENV NEXT_PUBLIC_TELEGRAM_BOT_USERNAME=${NEXT_PUBLIC_TELEGRAM_BOT_USERNAME}
ENV TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ENV TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET}
ENV TELEGRAM_USER_SECRET=${TELEGRAM_USER_SECRET}
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV PORT=${PORT}

# Отключаем телеметрию Next.js
ENV NEXT_TELEMETRY_DISABLED=1

# Собираем приложение
RUN npm run build

# Открываем порт
EXPOSE ${PORT}

# Запускаем приложение
CMD ["node", ".next/standalone/server.js"]
