name: Deploy to Railway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_WEBHOOK_SECRET: ${{ secrets.TELEGRAM_WEBHOOK_SECRET }}
          TELEGRAM_USER_SECRET: ${{ secrets.TELEGRAM_USER_SECRET }}
          NEXT_PUBLIC_TELEGRAM_BOT_USERNAME: ${{ secrets.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: |
          # Установка переменных окружения в Railway
          railway link
          railway variables set NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
          railway variables set NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
          railway variables set SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY
          railway variables set DATABASE_URL=$DATABASE_URL
          railway variables set TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
          railway variables set TELEGRAM_WEBHOOK_SECRET=$TELEGRAM_WEBHOOK_SECRET
          railway variables set TELEGRAM_USER_SECRET=$TELEGRAM_USER_SECRET
          railway variables set NEXT_PUBLIC_TELEGRAM_BOT_USERNAME=$NEXT_PUBLIC_TELEGRAM_BOT_USERNAME
          railway variables set NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
          railway variables set FRONTEND_URL=$FRONTEND_URL
          
          # Деплой приложения
          railway up
